import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Stickynav from "./components/navcomponents/StickyNav";
import OccasionBar from "./components/navcomponents/OccasionsBar";
import Topline from "./components/navcomponents/Topline";
import PhoneHeader from "./components/navcomponents/Phoneheader";
import GoToTopButton from "./components/GoToTopButton";
import MobileNavbar from "./components/navcomponents/MobileNav";
import Footer from "./components/Footer";
import Provider from "./components/Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
     
    >
      <body className="min-h-full flex flex-col"  suppressHydrationWarning={true}>
       <Provider>
        <GoToTopButton />
       <PhoneHeader/>
        <Topline/>
        <Navbar/>
         <MobileNavbar />
        <Stickynav/>
             
        {children}
        <Footer/>
        </Provider>
        </body>
    </html>
  );
}
